Ojaile.Consume/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Petify.Consume.Models;
using System.Text;

namespace Petify.Consume.Controllers
{
    public class AuthController : Controller
    {
        private readonly IConfiguration _configuration;
        string apiUrl;
        IHttpContextAccessor _httpContextAccessor;

        public AuthController(IConfiguration configuration,IHttpContextAccessor httpContextAccessor)
        {
            _configuration = configuration;
            apiUrl = _configuration.GetValue<string>("BaseUrl");
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Login()
        {
            Models.LoginViewModel vm = new Models.LoginViewModel();
            return View(vm);

        }

        [HttpPost]
        public async Task<IActionResult> Login([FromForm] LoginViewModel model)
        {
            StringContent content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");
            string endpoint = apiUrl + "HumanAccount/Login";
            using (HttpClient client = new HttpClient())
            {
                var Response = await client.PostAsync(endpoint, content);



                if (Response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    var response = await Response.Content.ReadAsStringAsync();
                    var result = JsonConvert.DeserializeObject<LoginTokenise>(response);
                    var access_token = _httpContextAccessor.HttpContext.Request.Cookies["access_token"];

                    Set("access_token", result.token, 30);
                    Set("first_name", result.firstname, 30);
                    Set("last_name", result.lastname, 30);
                    Set("email", result.email, 30);
                    Set("user_name", result.username, 30);


                    //TempData["token"] = result;// JsonConvert.DeserializeObject<string>(result);
                    TempData["LoginSuccess"] = "Login Sucessfull !";
                    client.Dispose ();
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.Clear();
                    ModelState.AddModelError(string.Empty, "Username or password incorrect");
                    return View();
                }
            }

        }

        [HttpGet]
        public async Task<IActionResult> Register()
        {
            AuthModelComponents authModelComponents = new AuthModelComponents();
            authModelComponents.user = new RegisterViewModel();
            string endpoint = apiUrl + "HumanAccount/GetUsers";
            using (HttpClient client = new HttpClient())
            {
                var response = await client.GetAsync(endpoint);
                var content = await response.Content.ReadAsStringAsync();
                authModelComponents.register = JsonConvert.DeserializeObject<List<RegisterViewModel>>(content);

            }

            return View(authModelComponents);
        }

        [HttpPost]
        public async Task<IActionResult> Register([FromForm] AuthModelComponents model)
        {
            StringContent content = new StringContent(JsonConvert.SerializeObject(model.user), Encoding.UTF8, "application/json");
            string endpoint = apiUrl + "HumanAccount/Register"; ;
            using (HttpClient client = new HttpClient())
            {
                var Response = await client.PostAsync(endpoint, content);



                if (Response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    //TempData["Profile"] = JsonConvert.SerializeObject(model);
                    return RedirectToAction("Login");
                }
                else
                {
                    ModelState.Clear();
                    ModelState.AddModelError(string.Empty, "Username already exist");
                    return View();
                }
            }
        }

        public async Task<IActionResult> Logout()
        {
            Remove("access_token");
            Remove("first_name");
            Remove("last_name");
            Remove("user_name");
            return RedirectToAction("Login");
        }

        public void Set(string key, string value, int? expireTime)
        {
            CookieOptions options = new CookieOptions();
            if (expireTime.HasValue)
                options.Expires = DateTime.Now.AddMinutes(expireTime.Value);
            else
                options.Expires = DateTime.Now.AddMinutes(10);
            Response.Cookies.Append(key, value, options);
        }

        public void Remove(string key)
        {
            Response.Cookies.Delete(key);
        }
    }
}

Ojaile.Consume/Controllers/ManageBookingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Petify.Consume.Models;
using Petify.Core.Model;
using System.Net.Http.Headers;
using System.Text;

namespace Petify.Consume.Controllers
{
    public class ManageBookingController : Controller
    {
        private readonly IConfiguration _configuration;
        string apiUrl;

        public ManageBookingController(IConfiguration configuration)
        {
            _configuration = configuration;
            apiUrl = _configuration.GetValue<string>("BaseUrl");
        }

        public async Task<IActionResult> Index()
        {
            BookingComponents bookingComponents = new BookingComponents();
            bookingComponents.booking = new Core.Model.BookingViewModel();
            string endpoint = apiUrl + "ManageBooking/GetAllBookings";

            var token = Request.Cookies["access_token"].ToString();


            string endpointServices = apiUrl + "ManageServices/RetrieveServices";

            List<ServiceViewModel>  serviceViews = new List<ServiceViewModel>();

            using (HttpClient client = new HttpClient())
            {

                client.BaseAddress = new Uri(endpointServices);
                client.DefaultRequestHeaders.Authorization =
               new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                // HttpResponseMessage response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead);
                var response = await client.GetAsync(endpointServices); //this get response from 
                if (response.IsSuccessStatusCode)
                {
                    var content = await response.Content.ReadAsStringAsync();
                    serviceViews = JsonConvert.DeserializeObject<List<ServiceViewModel>>(content);
                }
            }


            ViewBag.Service = serviceViews.Select(i => new SelectListItem
            {
                Value = i.Id.ToString(),
                Text = i.ServiceName,
                
            }).ToList();


            var handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false
            };

            using (HttpClient client = new HttpClient(handler))
            {
                client.BaseAddress = new Uri(endpoint);
                client.DefaultRequestHeaders.Authorization =
               new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var response = await client.GetAsync(endpoint); //this get response from 
                if (response.IsSuccessStatusCode)
                {
                    var content = await response.Content.ReadAsStringAsync();
                    bookingComponents.bookings = JsonConvert.DeserializeObject<List<BookingViewModel>>(content);
                }
            }
            return View(bookingComponents);
        }

        [HttpPost]
        public async Task<IActionResult> CreateBooking([FromForm] BookingComponents model)
        {
            //model.booking.ServiceId = 3;
           // model.booking.BillingId = 3;

            StringContent content = new StringContent(JsonConvert.SerializeObject(model.booking), Encoding.UTF8, "application/json");
            string endpoint = apiUrl + "ManageBooking/RequestBookingService";

            var token = Request.Cookies["access_token"].ToString();

            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(endpoint);
                client.DefaultRequestHeaders.Authorization =
                    new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var Response = await client.PostAsync(endpoint, content);



                if (Response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    TempData["user"] = model.booking.CreatedBy;
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.Clear();
                    ModelState.AddModelError(string.Empty, "Username already exist");
                    return RedirectToAction("Index");
                }
            }
        }
    }
}

Ojaile.Consume/Controllers/ManageCheckingController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Petify.Consume.Models;
using Petify.Core.Model;
using System.Net.Http.Headers;
using System.Text;

namespace Petify.Consume.Controllers
{
    public class ManageCheckingController : Controller
    {
        private readonly IConfiguration _configuration;
        string apiUrl;

        public ManageCheckingController(IConfiguration configuration)
        {
            _configuration = configuration;
            apiUrl = _configuration.GetValue<string>("BaseUrl");
        }

        public async Task<IActionResult> Index()
        {

            CheckingModelComponents  checkingComponents = new CheckingModelComponents();
            checkingComponents.checking = new CheckingViewModel();
            string endpoint = apiUrl + "ManageChecking/GetAllChecking";

            var token = Request.Cookies["access_token"].ToString();

            var handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false
            };

            using (HttpClient client = new HttpClient(handler))
            {
                client.BaseAddress = new Uri(endpoint);
                client.DefaultRequestHeaders.Authorization =
               new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var response = await client.GetAsync(endpoint); //this get response from 
                if (response.IsSuccessStatusCode)
                {
                    var content = await response.Content.ReadAsStringAsync();
                    checkingComponents.checkings = JsonConvert.DeserializeObject<List<CheckingViewModel>>(content);
                }
            }

            return View(checkingComponents);
        }


        [HttpPost]
        public async Task<IActionResult> AddChecking([FromForm] CheckingModelComponents model)
        {
            StringContent content = new StringContent(JsonConvert.SerializeObject(model.checking), Encoding.UTF8, "application/json");
            string endpoint = apiUrl + "ManageChecking/CreateChecking";

            var token = Request.Cookies["access_token"].ToString();

            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(endpoint);
                client.DefaultRequestHeaders.Authorization =
                    new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var Response = await client.PostAsync(endpoint, content);



                if (Response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                   // TempData["user"] = model.booking.CreatedBy;
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.Clear();
                    ModelState.AddModelError(string.Empty, "Username already exist");
                    return RedirectToAction("Index");
                }
            }
        }

    }
}

Ojaile.Consume/Controllers/ManageFeedBackController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Petify.Consume.Models;
using Petify.Core.Model;
using System.Net.Http.Headers;
using System.Text;

namespace Petify.Consume.Controllers
{
    public class ManageFeedBackController : Controller
    {
        private readonly IConfiguration _configuration;
        string apiUrl;
        public ManageFeedBackController(IConfiguration configuration)
        {
            _configuration = configuration;
            apiUrl = _configuration.GetValue<string>("BaseUrl");
        }

        public async Task<IActionResult> Index()
        {
            FeedBackModelComponents feedBackModelComponents = new FeedBackModelComponents();
            feedBackModelComponents.feedback = new FeedBackViewModel();
            string endpoint = apiUrl + "ManageFeedback/RetrieveFeedBacks";

            var token = Request.Cookies["access_token"].ToString();
            var handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false,
            };

            using (HttpClient client = new HttpClient(handler))
            {

                client.BaseAddress = new Uri(endpoint);
                client.DefaultRequestHeaders.Authorization =
               new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                // HttpResponseMessage response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead);
                var response = await client.GetAsync(endpoint); //this get response from 
                if (response.IsSuccessStatusCode)
                {
                    var content = await response.Content.ReadAsStringAsync();
                    feedBackModelComponents.feedbacks = JsonConvert.DeserializeObject<List<FeedBackViewModel>>(content);
                }
            }


            return View(feedBackModelComponents);
        }

        [HttpPost]
        public async Task<IActionResult> SendFeedBack ([FromForm] FeedBackModelComponents model)
        {

            StringContent content = new StringContent(JsonConvert.SerializeObject(model.feedback), Encoding.UTF8, "application/json");
            string endpoint = apiUrl + "ManageFeedback/CreatingFeedback";
            var token = Request.Cookies["access_token"].ToString();
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(endpoint);
                client.DefaultRequestHeaders.Authorization =
                    new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var Response = await client.PostAsync(endpoint, content);



                if (Response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    //TempData["Profile"] = JsonConvert.SerializeObject(model);
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.Clear();
                    ModelState.AddModelError(string.Empty, "Username already exist");
                    return RedirectToAction("Index");
                }
            }
        }
    }
}

Ojaile.Consume/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Petify</title>

    <!-- slider stylesheet -->
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css?family=Dosis:400,500|Poppins:400,700&display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="~/css/responsive.css" rel="stylesheet" />
</head>

<!-- footer section -->
<body>

    <header class="header_section">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg custom_nav-container ">
                <a class="navbar-brand"  asp-controller="Home" asp-action="Index">
                    <img src="images/logo.png" alt="">
                    <span>
                        Petify
                    </span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <div class="d-flex mx-auto flex-column flex-lg-row align-items-center">
                        <ul class="navbar-nav  ">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" style="font-size:15px">Home</a>
                            </li>

                            @if (Context.Request.Cookies["access_token"] == null)
                            {

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register" style="font-size:15px">Register</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login" style="font-size:15px">Login</a>
                                </li>
                            }

                            else
                            {
                                 <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ManagePetProfile" asp-action="Index" style="font-size:15px">Pet Profile</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ManageBooking" asp-action="Index" style="font-size:15px">Booking</a>
                                </li>

                                 <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ManageChecking" asp-action="Index" style="font-size:15px">Checking</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ManageFeedBack" asp-action="Index" style="font-size:15px">FeedBack</a>
                                </li>

                                 <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout" style="font-size:15px">Logout</a>
                                </li>

                               
                            }
                            @*

                            <li class="nav-item">
                                <a class="nav-link" href="pet.html" style="font-size:15px">Pet's gallery </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="contact.html" style="font-size:15px">Contact us</a>
                            </li>
                            
                                <li class="nav-item">
                                <a class="nav-link" href="buy.html" style="font-size:15px"> Buy now </a>
                                </li>*@
                        </ul>
                        @*
                        <form class="form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0">
                            <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
                        </form>*@
                    </div>
                    <div class="quote_btn-container  d-flex justify-content-center">
                        <a href="">
                            Call: +234 9022004674
                        </a>
                    </div>
                </div>
            </nav>
        </div>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>

    <script type="text/javascript" src="~/js/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="~/js/bootstrap.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>


    <script>
        // This example adds a marker to indicate the position of Bondi Beach in Sydney,
        // Australia.
        function initMap() {
          var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 11,
            center: {
              lat: 40.645037,
              lng: -73.880224
            },
          });

          var image = 'images/maps-and-flags.png';
          var beachMarker = new google.maps.Marker({
            position: {
              lat: 40.645037,
              lng: -73.880224
            },
            map: map,
            icon: image
          });
        }
    </script>
    <!-- google map js -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8eaHt9Dh5H57Zh0xVTqxVdBFCvFMqFjQ&callback=initMap">
    </script>
    <!-- end google map js -->
    @await RenderSectionAsync("Scripts", required: false)
</body>


</html>